name: FastAPI CI Pipeline

# when CI should run: every push and pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# tasks to execute
jobs:
  test:
    runs-on: ubuntu-latest  # Creates temporary Ubuntu machine in GitHub server
    steps:
      - name: Checkout Action  
      # prebuilt reusable action provided by Github
        uses: actions/checkout@v4    # temp machine - Download your repository code into the CI runner machine
      - name: Setup python
        uses: actions/setup-python@v5  # Install Python
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: 
          pip install -r requirements.txt   # Install dependencies
      - name:
        run: pytest   # Run pytest